
name: AutoRestTest CI

on:
  push:
    branches:
      - main

jobs:
  run-autoresttest:
    runs-on: ubuntu-latest
    environment: "AutoRestTest Web"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AutoRestTest
        run: |
          set -e

          if [ ! -f "market.json" ]; then
            echo "Error: Spec file not found at market.json"
            exit 1
          fi
          # Use Node to read and stringify the JSON spec, which is more robust than using shell commands.

          PAYLOAD=$(node -e "
            const fs = require('fs');
            const spec = require('./market.json');
            const data = {
              spec,
              config: market.json,
              user_id: 'user_34JbEVSt2M9RUA7qaBE2SYPQ85z'
            };
            console.log(JSON.stringify(data));
          ")

          curl -X POST https://unprofanely-nonnocturnal-latonya.ngrok-free.app/api/v1/jobs \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.AUTORESTTEST_API_KEY }}" \
            -d "$PAYLOAD"
